apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: saka
resources:
  - namespace.yaml
  - searxng.yaml
  - saka.yaml
images:
  - name: saka
    newName: saka
    newTag: local
