apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: {{ include "saka.namespace" . }}
  labels:
    app.kubernetes.io/name: searxng
    app.kubernetes.io/part-of: saka
data:
  settings.yml: |
{{ .Values.searxng.settings | indent 4 }}
